# Generated by cstruct-stubgen
from typing import BinaryIO, Literal, TypeAlias, overload

import dissect.cstruct as __cs__

class _c_tibx(__cs__.cstruct):
    PAGE_SIZE: Literal[4096] = ...
    class PageType(__cs__.Enum):
        ARCH = ...
        ARCI = ...
        LEAF = ...
        LDIR = ...
        GOLOMB = ...
        DATA = ...

    class EncrAlg(__cs__.Enum):
        NONE = ...
        AES_128_CBC = ...
        AES_192_CBC = ...
        AES_256_CBC = ...
        GOST2015 = ...
        AES_128_GCM = ...
        AES_192_GCM = ...
        AES_256_GCM = ...

    class ComprLvl(__cs__.Enum):
        NONE = ...
        LOW = ...
        NORMAL = ...
        HIGH = ...

    class page_header(__cs__.Structure):
        marker: _c_tibx.uint8
        type: _c_tibx.PageType
        _pad: _c_tibx.uint16
        crc32c: _c_tibx.uint32
        @overload
        def __init__(self, marker: _c_tibx.uint8 | None = ..., type: _c_tibx.PageType | None = ..., _pad: _c_tibx.uint16 | None = ..., crc32c: _c_tibx.uint32 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class arch_superblock(__cs__.Structure):
        header: _c_tibx.page_header
        magic: __cs__.CharArray
        header_size: _c_tibx.uint32
        header_version: _c_tibx.uint16
        compr_lvl: _c_tibx.ComprLvl
        encr_alg: _c_tibx.EncrAlg
        dedup: _c_tibx.uint8
        hash_alg: _c_tibx.uint8
        chunking_alg: _c_tibx.uint8
        hash_window_width: _c_tibx.uint8
        created_ms: _c_tibx.uint64
        modified_ms: _c_tibx.uint64
        archive_uuid: __cs__.CharArray
        @overload
        def __init__(self, header: _c_tibx.page_header | None = ..., magic: __cs__.CharArray | None = ..., header_size: _c_tibx.uint32 | None = ..., header_version: _c_tibx.uint16 | None = ..., compr_lvl: _c_tibx.ComprLvl | None = ..., encr_alg: _c_tibx.EncrAlg | None = ..., dedup: _c_tibx.uint8 | None = ..., hash_alg: _c_tibx.uint8 | None = ..., chunking_alg: _c_tibx.uint8 | None = ..., hash_window_width: _c_tibx.uint8 | None = ..., created_ms: _c_tibx.uint64 | None = ..., modified_ms: _c_tibx.uint64 | None = ..., archive_uuid: __cs__.CharArray | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class segment_header(__cs__.Structure):
        magic: __cs__.CharArray
        version: _c_tibx.uint16
        length: _c_tibx.uint32
        zlength: _c_tibx.uint32
        key_id: _c_tibx.uint32
        compression: _c_tibx.uint16
        cache: _c_tibx.uint16
        @overload
        def __init__(self, magic: __cs__.CharArray | None = ..., version: _c_tibx.uint16 | None = ..., length: _c_tibx.uint32 | None = ..., zlength: _c_tibx.uint32 | None = ..., key_id: _c_tibx.uint32 | None = ..., compression: _c_tibx.uint16 | None = ..., cache: _c_tibx.uint16 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class lsm_superblock(__cs__.Structure):
        magic: __cs__.CharArray
        format_version: _c_tibx.uint8
        ctree_count_minus_2: _c_tibx.uint8
        ctree_max_minus_2: _c_tibx.uint8
        _reserved0: _c_tibx.uint8
        seq: _c_tibx.uint32
        ctree_size_hint: _c_tibx.uint32
        key_length: _c_tibx.uint32
        value_length: _c_tibx.uint32
        @overload
        def __init__(self, magic: __cs__.CharArray | None = ..., format_version: _c_tibx.uint8 | None = ..., ctree_count_minus_2: _c_tibx.uint8 | None = ..., ctree_max_minus_2: _c_tibx.uint8 | None = ..., _reserved0: _c_tibx.uint8 | None = ..., seq: _c_tibx.uint32 | None = ..., ctree_size_hint: _c_tibx.uint32 | None = ..., key_length: _c_tibx.uint32 | None = ..., value_length: _c_tibx.uint32 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class ctree_ref(__cs__.Structure):
        offset: _c_tibx.uint64
        num_pages: _c_tibx.uint64
        item_count: _c_tibx.uint32
        _reserved: _c_tibx.uint32
        max_key_or_size: _c_tibx.uint64
        @overload
        def __init__(self, offset: _c_tibx.uint64 | None = ..., num_pages: _c_tibx.uint64 | None = ..., item_count: _c_tibx.uint32 | None = ..., _reserved: _c_tibx.uint32 | None = ..., max_key_or_size: _c_tibx.uint64 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class lsm_memtree_header(__cs__.Structure):
        encoding: _c_tibx.uint8
        _reserved: _c_tibx.uint8
        node_count: _c_tibx.uint16
        extra_len: _c_tibx.uint32
        pages_total: _c_tibx.uint32
        @overload
        def __init__(self, encoding: _c_tibx.uint8 | None = ..., _reserved: _c_tibx.uint8 | None = ..., node_count: _c_tibx.uint16 | None = ..., extra_len: _c_tibx.uint32 | None = ..., pages_total: _c_tibx.uint32 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class lsm_page_header(__cs__.Structure):
        magic: __cs__.CharArray
        version: _c_tibx.uint8
        encoding: _c_tibx.uint8
        cell_count: _c_tibx.uint16
        uncompressed_size: _c_tibx.uint32
        on_disk_size: _c_tibx.uint32
        key_size_param: _c_tibx.uint32
        _sequence_id: __cs__.CharArray
        @overload
        def __init__(self, magic: __cs__.CharArray | None = ..., version: _c_tibx.uint8 | None = ..., encoding: _c_tibx.uint8 | None = ..., cell_count: _c_tibx.uint16 | None = ..., uncompressed_size: _c_tibx.uint32 | None = ..., on_disk_size: _c_tibx.uint32 | None = ..., key_size_param: _c_tibx.uint32 | None = ..., _sequence_id: __cs__.CharArray | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class data_map_key(__cs__.Structure):
        volume_id: _c_tibx.uint64
        source_offset: _c_tibx.uint64
        extent_length: _c_tibx.uint24
        slice_id: _c_tibx.uint32
        extent_id: _c_tibx.uint64
        @overload
        def __init__(self, volume_id: _c_tibx.uint64 | None = ..., source_offset: _c_tibx.uint64 | None = ..., extent_length: _c_tibx.uint24 | None = ..., slice_id: _c_tibx.uint32 | None = ..., extent_id: _c_tibx.uint64 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class data_map_value(__cs__.Structure):
        segment_id: _c_tibx.uint64
        extent_index: _c_tibx.uint16
        @overload
        def __init__(self, segment_id: _c_tibx.uint64 | None = ..., extent_index: _c_tibx.uint16 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class wrapped_key(__cs__.Structure):
        format: _c_tibx.uint8
        alg: _c_tibx.uint8
        iter_log2: _c_tibx.uint8
        _reserved: _c_tibx.uint8
        salt: __cs__.CharArray
        @overload
        def __init__(self, format: _c_tibx.uint8 | None = ..., alg: _c_tibx.uint8 | None = ..., iter_log2: _c_tibx.uint8 | None = ..., _reserved: _c_tibx.uint8 | None = ..., salt: __cs__.CharArray | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class file_table_entry(__cs__.Structure):
        index: _c_tibx.uint32
        byte_offset: _c_tibx.uint64
        @overload
        def __init__(self, index: _c_tibx.uint32 | None = ..., byte_offset: _c_tibx.uint64 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

# Technically `c_tibx` is an instance of `_c_tibx`, but then we can't use it in type hints
c_tibx: TypeAlias = _c_tibx
